name: active_storage
description: Send files to a Rails Active Storage backend using direct upload
version: 1.1.0
homepage: https://www.algonauti.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  crypto: ^3.0.2

dev_dependencies:
  test: ^1.21.1
