name: active_storage
description: Send files to a Rails Active Storage backend using direct upload
version: 0.2.0
author: Algonauti <info@algonauti.com>
homepage: https://www.algonauti.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  http: ^0.13.3
  crypto: ^3.0.1

dev_dependencies:
  test: ^1.17.3
